name    'narkisr-storm'
version '0.0.1'
source 'UNKNOWN'
author 'narkisr'
license 'UNKNOWN'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
